server {
    listen 80;
    index index.php index.html;
    root /var/www/public;           # Laravelの公開ディレクトリ（index.phpの場所）

client_header_buffer_size   16k;
    large_client_header_buffers 8 32k;
    location / {
        # URLに対応する静的ファイルがなければ index.php（Laravel）に転送
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;      # PHP-FPMコンテナ（app）へ処理を転送
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ /\.ht {
        deny all;                   # .htaccess などの隠しファイルへのアクセスを拒否
    }
}